---
- name: Create monitoring user
  ansible.builtin.user:
    name: "{{ monitoring_user  }}"
    home: "{{ shared_home_storage  }}/{{ monitoring_user  }}"
    move_home: yes
    create_home: yes
    shell: /bin/bash

- name: Edit .bashrc file
  ansible.builtin.blockinfile:
    path: "{{ shared_home_storage  }}/{{ monitoring_user }}/.bashrc"
    block: |
      alias rcedit="vim $HOME/.bashrc"
      alias rcsource="source $HOME/.bashrc"
      alias c="clear"
      PS1='\[\e[1;37m\](\h)\[\e[0m\]:\[\e[0;31m\](\u)\[\e[0m\]:\[\e[38;5;208m\]\w\[\e[0m\] \[\e[1;37m\]-> \[\e[0m\]'
      # Enable color support for ls and other commands
      if [ -x /usr/bin/dircolors ]; then
          test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
      fi
      alias ls='ls --color=auto'
      alias ll='ls -alF'
      alias la='ls -A'
      alias l='ls -CF'
      alias q="squeue -u $USER"
      PS1='\[\e[1;37m\](\h)\[\e[0m\]:\[\e[0;31m\](\u)\[\e[0m\]:\[\e[38;5;208m\]\w\[\e[0m\] \[\e[1;37m\]-> \[\e[0m\]'
      export MODULEPATH=/mnt/nfs/software/modules:$MODULEPATH
  become: yes

- name: Edit .bash_profile file
  ansible.builtin.blockinfile:
    path: "{{ shared_home_storage  }}/{{ monitoring_user  }}/.bash_profile"
    block: |
      if [ -f $HOME/.bashrc  ]; then
          . $HOME/.bashrc
      fi
    create: yes
  become: yes

- name: Ensure monioring directory exists
  ansible.builtin.file:
    path: "{{  shared_storage  }}/monitoring"
    state: directory
    owner: "{{ monitoring_user  }}"
    group: "{{ monitoring_user  }}"
    mode: '0755'
  become: yes

- name: Clone git repository
  ansible.builtin.shell: |
    set -e
    cd {{  shared_storage  }}/monitoring
    git clone {{ monitoring_repo  }} monitoring_repo
  args:
    creates: "{{  shared_storage  }}/monitoring/monitoring_repo"
  become: yes

- name: Set ownership for monitoring directory
  ansible.builtin.file:
    path: "{{  shared_storage  }}/monitoring"
    owner: "{{ monitoring_user  }}"
    group: "{{ monitoring_user  }}"
    recurse: yes
    state: directory
  become: yes



