---
- name: Ensure OpenMPI source directory exists
  ansible.builtin.file:
    path: "{{ shared_software_path }}/source/openmpi/{{ openmpi_version }}"
    owner: "{{ shared_software_user }}"
    group: "{{ shared_software_user }}"
    mode: '0755'
    state: directory

- name: Ensure OpenMPI apps directory exists
  ansible.builtin.file:
    path: "{{ shared_software_path }}/apps/openmpi/{{ openmpi_version }}"
    owner: "{{ shared_software_user }}"
    group: "{{ shared_software_user }}"
    mode: '0755'
    state: directory

- name: Download OpenMPI source tarball
  ansible.builtin.get_url:
    url: "https://download.open-mpi.org/release/open-mpi/v{{ openmpi_version.split('.')[0] }}/openmpi-{{ openmpi_version }}.tar.gz"
    dest: "{{ shared_software_path }}/source/openmpi/{{ openmpi_version }}/openmpi-{{ openmpi_version }}.tar.gz"
    mode: '0644'
  become: yes

- name: Extract OpenMPI source
  ansible.builtin.unarchive:
    src: "{{ shared_software_path }}/source/openmpi/{{ openmpi_version }}/openmpi-{{ openmpi_version }}.tar.gz"
    dest: "{{ shared_software_path }}/source/openmpi"
    remote_src: yes
    creates: "{{ shared_software_path }}/source/openmpi-{{ openmpi_version }}"
  become: yes
