[guacamole]
guacamole ansible_host=34.219.12.163 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

[login]
login ansible_host=44.248.109.58 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519 

[compute]
compute ansible_host=34.219.20.28 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

[storage]
storage ansible_host=35.88.196.30 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

[shared_storage]
compute ansible_host=34.219.20.28 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519
login ansible_host=44.248.109.58 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

[slurm]
compute ansible_host=34.219.20.28 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519
login ansible_host=44.248.109.58 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

[shared_software]
login ansible_host=44.248.109.58 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519
