[login]
login ansible_host=35.167.132.206 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519 

[compute]
compute ansible_host=16.146.54.43 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

[storage]
storage ansible_host=44.254.107.37 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

[shared_storage]
compute ansible_host=16.146.54.43 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519
login ansible_host=35.167.132.206 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

[slurm]
compute ansible_host=16.146.54.43 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519
login ansible_host=35.167.132.206 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

[shared_software]
login ansible_host=35.167.132.206 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519
