---
- name: Ensure all relevant packages are installed
  ansible.builtin.apt:
    name:
      - squashfuse 
      - fuse2fs 
      - gocryptfs

- name: Create Apptainer install directory
  ansible.builtin.file:
    path: "{{ shared_software_path }}/apps/apptainer/{{ apptainer_version }}"
    owner: "{{ shared_software_user }}"
    group: "{{ shared_software_user }}"
    mode: '0755'
    state: directory

- name: Ensure Go workspace exists
  ansible.builtin.file:
    path: "/tmp/go"
    state: directory
    mode: '0755'

- name: Clone Apptainer GitHub repo
  ansible.builtin.shell: |
    set -e
    cd {{ shared_software_path }}/source/
    git clone https://github.com/apptainer/apptainer.git apptainer/{{  apptainer_version }}
    cd apptainer/{{  apptainer_version }}
    git fetch --all
    git checkout v{{ apptainer_version }}
  args:
    creates: "{{ shared_software_path }}/source/apptainer/{{  apptainer_version }}"
  become: yes

- name: Build and install Apptainer
  ansible.builtin.shell: |
    set -e
    cd {{ shared_software_path }}/source/apptainer/{{ apptainer_version }}
    ./mconfig --prefix={{ shared_software_path }}/apps/apptainer/{{ apptainer_version }}
    cd builddir
    make -j $(nproc)
    make install
  args:
    creates: "{{ shared_software_path }}/apps/apptainer/{{ apptainer_version }}/bin/apptainer"
  become: yes

- name: Set ownership for Apptainer installation
  ansible.builtin.file:
    path: "{{ shared_software_path }}/apps/apptainer"
    owner: "{{ shared_software_user }}"
    group: "{{ shared_software_user }}"
    recurse: yes
    state: directory

- name: Ensure Apptainer module directory exists
  ansible.builtin.file:
    path: "{{ shared_software_path }}/modules/apptainer"
    owner: "{{ shared_software_user }}"
    group: "{{ shared_software_user }}"
    mode: '0755'
    state: directory

- name: Create Apptainer modulefile
  ansible.builtin.copy:
    dest: "{{ shared_software_path }}/modules/apptainer/{{ apptainer_version }}.lua"
    owner: "{{ shared_software_user }}"
    group: "{{ shared_software_user }}"
    mode: '0755'
    content: |
      -- Lua module file for Apptainer {{ apptainer_version }}
      prepend_path("PATH", "{{ shared_software_path }}/apps/apptainer/{{ apptainer_version }}/bin")
      prepend_path("MANPATH", "{{ shared_software_path }}/apps/apptainer/{{ apptainer_version }}/share/man")